ALL:

CFLAGS	        = 
FFLAGS	        =  
CPPFLAGS        =  
CPPFLAGS        = 
CLEANFILES      = 

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

# your targets if any

include ${PETSC_DIR}/lib/petsc/conf/test 
